# Generated by Django 2.1.1 on 2018-10-28 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_auto_20181026_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsuser',
            name='name',
        ),
    ]
