# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-26 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rzd_Parser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('code', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=250)),
                ('link', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
