# Generated by Django 2.0.3 on 2018-03-20 13:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RzdTenders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='http://etzp.rzd.ru/freeccee/main?ACTION=searchProc', max_length=250)),
                ('query_string', models.CharField(max_length=250)),
                ('bid_deadlin_from', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='TenderDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_title', models.CharField(max_length=250)),
                ('doc_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Tenders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=350)),
                ('customer', models.CharField(max_length=250)),
                ('price', models.CharField(max_length=250)),
                ('deadline', models.DateTimeField()),
                ('link', models.URLField()),
                ('rzd_tenders_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='found_tenders', to='tenders.RzdTenders')),
            ],
        ),
        migrations.AddField(
            model_name='tenderdocuments',
            name='tender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_links', to='tenders.Tenders'),
        ),
    ]
