# Generated by Django 2.0.3 on 2018-03-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0004_auto_20180323_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenders',
            name='deadline',
            field=models.CharField(max_length=20),
        ),
    ]
