# Generated by Django 2.0.3 on 2018-03-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0006_auto_20180327_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rzdtenders',
            name='bid_deadlin_from',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
