# Generated by Django 2.0.3 on 2018-03-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0009_auto_20180327_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rzdtenders',
            name='bid_deadlin_from',
            field=models.CharField(max_length=50),
        ),
    ]
