# Generated by Django 2.0.3 on 2018-03-28 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0010_auto_20180327_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rzdtenders',
            options={'verbose_name': 'Тендер РЖД', 'verbose_name_plural': 'Тендеры РЖД'},
        ),
        migrations.AlterModelOptions(
            name='tenderdocuments',
            options={'verbose_name': 'Документ тендера', 'verbose_name_plural': 'Документы тендера'},
        ),
        migrations.AlterModelOptions(
            name='tenders',
            options={'verbose_name': 'Тендер', 'verbose_name_plural': 'Тендеры'},
        ),
        migrations.AlterField(
            model_name='rzdtenders',
            name='bid_deadlin_from',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Подача заявки с:'),
        ),
        migrations.AlterField(
            model_name='rzdtenders',
            name='query_string',
            field=models.CharField(max_length=250, verbose_name='Запрос'),
        ),
        migrations.AlterField(
            model_name='rzdtenders',
            name='url',
            field=models.CharField(default='http://etzp.rzd.ru/freeccee/main?ACTION=searchProc', max_length=250, verbose_name='Адрес запроса'),
        ),
        migrations.AlterField(
            model_name='tenderdocuments',
            name='doc_link',
            field=models.URLField(verbose_name='Ссылка на документ'),
        ),
        migrations.AlterField(
            model_name='tenderdocuments',
            name='doc_title',
            field=models.CharField(max_length=250, verbose_name='Название документа'),
        ),
        migrations.AlterField(
            model_name='tenderdocuments',
            name='tender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_links', to='tenders.Tenders', verbose_name='Тендер'),
        ),
        migrations.AlterField(
            model_name='tenders',
            name='code',
            field=models.CharField(max_length=100, verbose_name='Код тендера'),
        ),
        migrations.AlterField(
            model_name='tenders',
            name='customer',
            field=models.CharField(max_length=250, verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='tenders',
            name='deadline',
            field=models.CharField(max_length=20, verbose_name='Срок подачи заявок'),
        ),
        migrations.AlterField(
            model_name='tenders',
            name='link',
            field=models.URLField(verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='tenders',
            name='price',
            field=models.CharField(max_length=250, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='tenders',
            name='rzd_tenders_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='found_tenders', to='tenders.RzdTenders', verbose_name='Запрос тендера'),
        ),
        migrations.AlterField(
            model_name='tenders',
            name='subject',
            field=models.CharField(max_length=350, verbose_name='Предмет'),
        ),
    ]
