# Generated by Django 2.0.3 on 2018-03-29 12:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenders', '0011_auto_20180328_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenders',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
