# Generated by Django 2.0.3 on 2018-04-06 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0013_remove_tenders_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenders',
            name='rzd_tenders_request',
        ),
    ]
