# Generated by Django 2.0.3 on 2018-04-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0014_remove_tenders_rzd_tenders_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenderdocuments',
            name='tender',
        ),
        migrations.AddField(
            model_name='tenders',
            name='document_links',
            field=models.CharField(blank=True, max_length=2500, null=True, verbose_name='Тендерные документы'),
        ),
        migrations.AlterField(
            model_name='tenders',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Код тендера'),
        ),
        migrations.AlterField(
            model_name='tenders',
            name='customer',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='tenders',
            name='deadline',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Срок подачи заявок'),
        ),
        migrations.AlterField(
            model_name='tenders',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='tenders',
            name='price',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='tenders',
            name='subject',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Предмет'),
        ),
        migrations.DeleteModel(
            name='TenderDocuments',
        ),
    ]
