# Generated by Django 2.0.3 on 2018-04-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0015_auto_20180406_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenders',
            name='etp',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Торговая площадка'),
        ),
    ]
