# Generated by Django 2.0.3 on 2018-04-09 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0018_auto_20180406_1816'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RzdTenders',
        ),
    ]
