# Generated by Django 2.0.3 on 2018-04-11 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0019_delete_rzdtenders'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_title', models.CharField(max_length=250, verbose_name='Название документа')),
                ('doc_link', models.URLField(verbose_name='Ссылка на документ')),
            ],
            options={
                'verbose_name': 'Документ тендера',
                'verbose_name_plural': 'Документы тендера',
            },
        ),
        migrations.RemoveField(
            model_name='tenders',
            name='document_links',
        ),
        migrations.AddField(
            model_name='tenderdocuments',
            name='tender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_links', to='tenders.Tenders', verbose_name='Тендер'),
        ),
    ]
