# Generated by Django 2.0.3 on 2018-04-16 11:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0021_tenders_lots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenderdocuments',
            name='tender',
        ),
        migrations.AddField(
            model_name='tenders',
            name='document_links',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.DeleteModel(
            name='TenderDocuments',
        ),
    ]
