# Generated by Django 2.0.3 on 2018-04-17 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenders', '0022_auto_20180416_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteTenders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_tender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenders.Tenders', verbose_name='Избранный тендер')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
