# Generated by Django 2.0.3 on 2018-04-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0023_favoritetenders'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritetenders',
            options={'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранное'},
        ),
        migrations.AlterField(
            model_name='tenders',
            name='deadline',
            field=models.DateTimeField(blank=True, max_length=20, null=True, verbose_name='Срок подачи заявок'),
        ),
    ]
