# Generated by Django 2.0.3 on 2018-04-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0024_auto_20180422_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenders',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Срок подачи заявок'),
        ),
    ]
