# Generated by Django 2.0.3 on 2018-06-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0025_auto_20180422_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenders',
            name='in_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
