# Generated by Django 2.0.7 on 2018-07-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20180714_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_school',
            field=models.BooleanField(default=False),
        ),
    ]
