# Generated by Django 2.0.7 on 2018-07-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_company_is_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='is_school',
            field=models.BooleanField(default=False, verbose_name='Является школой'),
        ),
    ]
