# Generated by Django 2.0.7 on 2018-07-14 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20180714_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='company',
        ),
        migrations.RemoveField(
            model_name='studio',
            name='company',
        ),
        migrations.AddField(
            model_name='company',
            name='is_studio',
            field=models.BooleanField(default=False, verbose_name='Является студией'),
        ),
        migrations.AddField(
            model_name='company',
            name='other_condition',
            field=models.TextField(blank=True, verbose_name='Прочие условия (студия)'),
        ),
        migrations.AddField(
            model_name='company',
            name='own_animators',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='school_desctiption',
            field=models.TextField(blank=True, verbose_name='Описание школы'),
        ),
        migrations.AddField(
            model_name='company',
            name='studio_aria',
            field=models.FloatField(default=0, verbose_name='Площадь студии'),
        ),
        migrations.AddField(
            model_name='company',
            name='studio_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, verbose_name='Стоимость аренды'),
        ),
        migrations.AlterField(
            model_name='animator',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='std_animators', to='catalog.Company', verbose_name='Студия'),
        ),
        migrations.AlterField(
            model_name='schoolprogram',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sch_programs', to='catalog.Company', verbose_name='Школа'),
        ),
        migrations.DeleteModel(
            name='School',
        ),
        migrations.DeleteModel(
            name='Studio',
        ),
    ]
