# Generated by Django 2.0.7 on 2018-07-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20180714_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='other_condition',
            new_name='studio_condition',
        ),
        migrations.AlterField(
            model_name='company',
            name='own_animators',
            field=models.BooleanField(default=False, verbose_name='Есть свои аниматоры'),
        ),
    ]
