# Generated by Django 2.0.7 on 2018-07-25 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180725_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='url',
            new_name='sec_slug',
        ),
    ]
