# Generated by Django 2.0.7 on 2018-07-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180725_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='status',
        ),
        migrations.AlterField(
            model_name='article',
            name='allow_comments',
            field=models.BooleanField(default=True, verbose_name='Разрешены комментарии'),
        ),
    ]
