# Generated by Django 2.0.7 on 2018-07-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180725_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('черновик', 'Черновик'), ('опубликован', 'Опубликова')], default='черновик', max_length=11),
        ),
    ]
