# Generated by Django 2.0.7 on 2018-07-25 10:58

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_article_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Содержание поста'),
        ),
        migrations.AlterField(
            model_name='article',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Section', verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='article',
            name='seo_desription',
            field=models.CharField(blank=True, max_length=200, verbose_name='СЕО-описание'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('черновик', 'Черновик'), ('опубликован', 'Опубликова')], default='черновик', max_length=11, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='article',
            name='subsection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.Subsection', verbose_name='Подраздел'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
    ]
