# Generated by Django 2.0.7 on 2018-07-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180725_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('черновик', 'Черновик'), ('опубликован', 'Опубликован')], default='черновик', max_length=11, verbose_name='Статус'),
        ),
    ]
