# Generated by Django 2.0.7 on 2018-07-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180725_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='head_image',
            field=models.ImageField(blank=True, default=None, upload_to='post_images/'),
        ),
    ]
