# Generated by Django 2.0.7 on 2018-07-26 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_article_head_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='head_image',
        ),
    ]
