# Generated by Django 2.0.7 on 2018-07-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_article_head_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='sort_description',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
