# Generated by Django 2.0.7 on 2018-07-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_article_sort_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='sort_description',
        ),
        migrations.AddField(
            model_name='article',
            name='short_description',
            field=models.TextField(blank=True, max_length=200, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='article',
            name='head_image',
            field=models.ImageField(default='post_images/None/default_image_to_post.jpg', upload_to='post_images/', verbose_name='Изображение в шапке'),
        ),
    ]
