# Generated by Django 2.0.7 on 2018-07-26 16:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20180726_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата статистики')),
                ('views', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article', verbose_name='Статья')),
            ],
            options={
                'db_table': 'ArticalStatistic',
            },
        ),
    ]
