# Generated by Django 2.1.1 on 2018-10-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='head_image',
            field=models.ImageField(default='post_images/None/default_image.jpg', upload_to='post_images/', verbose_name='Изображение в шапке'),
        ),
    ]
