# Generated by Django 2.1.1 on 2018-10-22 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20181020_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlestatistic',
            options={'verbose_name': 'Статистика по статьям', 'verbose_name_plural': 'Статистики по статьям'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AddField(
            model_name='subsection',
            name='section',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='blog.Section'),
            preserve_default=False,
        ),
    ]
