# Generated by Django 2.1.1 on 2018-10-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20181022_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='order_range',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='subsection',
            name='order_range',
            field=models.IntegerField(default=100),
        ),
    ]
