# Generated by Django 2.1.1 on 2018-10-23 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20181023_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='order_range',
        ),
        migrations.RemoveField(
            model_name='subsection',
            name='order_range',
        ),
    ]
