# Generated by Django 2.1.1 on 2018-10-31 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20181023_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title',
        ),
        migrations.AddField(
            model_name='article',
            name='article_description',
            field=models.TextField(blank=True, max_length=200, verbose_name='Краткое описание статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_title',
            field=models.CharField(default='Новая статья', max_length=200, verbose_name='Заголовок статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=200, verbose_name='СЕО-keywords'),
        ),
        migrations.AddField(
            model_name='article',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='СЕО-title'),
        ),
    ]
